### ISSUE TITLE
Help regarding a implementation

### ISSUE THREAD

**Issue by sris3** [point85/ShiftSharp#3]
Thanks for this wonderful application. 

I have a requirement, where I have different teams or job title and each job titles have multiple employees. I need to create shift for these Job tiles, where we specify the number or required job title / people for each shift. 

Do we have any option to work this way ?

**Comment by point85** [comment]
Hello Sridhar,
The current ShiftSharp library does not have support for individual
people.  If I understand correctly, you need to have members assigned to a
team.  A team member would have attributes of employee ID, title, first
name, last name, etc.  The shift instance has a team which would have the
assigned members, but since people get sick, go on vacation, and trade
shifts, the shift instance would also need the collection of actual team
members.  Does this satisfy your requirements?

Regards,
Kent Randall

**Comment by sris3** [comment]
Thanks for your reply. My requirement is something different. 

Say there is a business having multiple departments (example we will consider a hotel)

1.  I have 3 shifts in my hotel. 
2. Where the requirement is 2 Chef for Day shift / 2 Chef for Night shift / 1 Chef for General Shift 
3. Also for these shifts i will require helpers so the same 1 Helper for Day Shift / 2 Helpers for Night Shift / 2 Helper for General Shift. 

So you can see the count of people required for each shift. And it has to be equally sharing across each employee. Say one who worked Night Shift , can be given Same Night shift or Day Off. 

Screenshots for reference 

![image](https://github.com/user-attachments/assets/0a8bf443-0c1a-4b91-aad0-074522a266fd)


Regards,
Sridhar Seshan

**Comment by point85** [comment]
I think the best way to sort out this requirement is for me to implement
some enhancements for you to try.  Could you send me your code with the
work schedule, shifts, teams and rotations for the hotel example?  I will
work on some enhancements for you to test.

Regards,
Kent Randall

**Comment by sris3** [comment]
Sure, Thanks will share the code which are currently implemented. Do we have any other mode to connect ? please let me know

**Comment by point85** [comment]
Let’s use my personal email account: ***@***.***  Thanks.Sent from my iPhoneOn Dec 11, 2024, at 9:40 AM, Sridhar Anehan ***@***.***> wrote:﻿
Sure, Thanks will share the code which are currently implemented. Do we have any other mode to connect ? please let me know

**Comment by sris3** [comment]
Sorry, i do not see the email id here. Please find my code below.

using Point85.ShiftSharp.Schedule;
using System;
using NodaTime;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Diagnostics;

namespace ShiftConsole
{
    internal class Program
    {
        static void Main(string[] args)
        {
            String description = "This is a fast rotation plan that uses 3 teams and two 12-hr shifts to provide 24/7 coverage. "
    + "Each team rotates through the following sequence every three days: 1 day shift, 1 night shift, and 1 day off.";

            WorkSchedule schedule = new WorkSchedule("DNO Plan", description);

            // Day shift, starts at 07:00 for 12 hours
            Shift day = schedule.CreateShift("Day", "Day shift", new LocalTime(7, 0, 0), Duration.FromHours(9));

            // Night shift, starts at 19:00 for 12 hours
            Shift night = schedule.CreateShift("Night", "Night shift", new LocalTime(16, 0, 0), Duration.FromHours(9));

            // rotation
            Rotation rotation = new Rotation();
            rotation.Name = "DNO";
            rotation.Description= "DNO";
            rotation.AddSegment(day, 1, 0);
            rotation.AddSegment(night, 1, 1);

            var referenceDate = new LocalDate(2017, 3, 1);

            schedule.CreateTeam("Sridhar", "Master Chef", rotation, referenceDate);
            schedule.CreateTeam("Rajesh", "Master Chef", rotation, referenceDate.Minus(Period.FromDays(1)));
            schedule.CreateTeam("Manoj", "Master Chef", rotation, referenceDate.Minus(Period.FromDays(2)));
            schedule.CreateTeam("Ezhil", "Master Chef", rotation, referenceDate.Minus(Period.FromDays(3)));
            schedule.CreateTeam("Ponram", "Master Chef", rotation, referenceDate.Minus(Period.FromDays(4)));

            string instances = schedule.BuildShiftInstances(new LocalDate(2017, 3, 1), new LocalDate(2017, 3, 30));
            Debug.WriteLine(instances);

        }
    }
}

here the "Master Chef" which is been mentioned in the Description is role/title for each employee. 

Below is the output I get from the code for a date range of **1st March 2017 to 30th March 2017**

[1] : Wednesday, March 1, 2017
   (1) Team: Sridhar, Shift: Day, Start: 03/01/2017 7:00:00 AM, End: 03/01/2017 4:00:00 PM
   (2) Team: Ezhil, Shift: Day, Start: 03/01/2017 7:00:00 AM, End: 03/01/2017 4:00:00 PM
   (3) Team: Rajesh, Shift: Night, Start: 03/01/2017 4:00:00 PM, End: 03/02/2017 1:00:00 AM
   (4) Team: Ponram, Shift: Night, Start: 03/01/2017 4:00:00 PM, End: 03/02/2017 1:00:00 AM
[2] : Thursday, March 2, 2017
   (1) Team: Manoj, Shift: Day, Start: 03/02/2017 7:00:00 AM, End: 03/02/2017 4:00:00 PM
   (2) Team: Sridhar, Shift: Night, Start: 03/02/2017 4:00:00 PM, End: 03/03/2017 1:00:00 AM
   (3) Team: Ezhil, Shift: Night, Start: 03/02/2017 4:00:00 PM, End: 03/03/2017 1:00:00 AM
[3] : Friday, March 3, 2017
   (1) Team: Rajesh, Shift: Day, Start: 03/03/2017 7:00:00 AM, End: 03/03/2017 4:00:00 PM
   (2) Team: Ponram, Shift: Day, Start: 03/03/2017 7:00:00 AM, End: 03/03/2017 4:00:00 PM
   (3) Team: Manoj, Shift: Night, Start: 03/03/2017 4:00:00 PM, End: 03/04/2017 1:00:00 AM
[4] : Saturday, March 4, 2017
   (1) Team: Sridhar, Shift: Day, Start: 03/04/2017 7:00:00 AM, End: 03/04/2017 4:00:00 PM
   (2) Team: Ezhil, Shift: Day, Start: 03/04/2017 7:00:00 AM, End: 03/04/2017 4:00:00 PM
   (3) Team: Rajesh, Shift: Night, Start: 03/04/2017 4:00:00 PM, End: 03/05/2017 1:00:00 AM
   (4) Team: Ponram, Shift: Night, Start: 03/04/2017 4:00:00 PM, End: 03/05/2017 1:00:00 AM
[5] : Sunday, March 5, 2017
   (1) Team: Manoj, Shift: Day, Start: 03/05/2017 7:00:00 AM, End: 03/05/2017 4:00:00 PM
   (2) Team: Sridhar, Shift: Night, Start: 03/05/2017 4:00:00 PM, End: 03/06/2017 1:00:00 AM
   (3) Team: Ezhil, Shift: Night, Start: 03/05/2017 4:00:00 PM, End: 03/06/2017 1:00:00 AM
[6] : Monday, March 6, 2017
   (1) Team: Rajesh, Shift: Day, Start: 03/06/2017 7:00:00 AM, End: 03/06/2017 4:00:00 PM
   (2) Team: Ponram, Shift: Day, Start: 03/06/2017 7:00:00 AM, End: 03/06/2017 4:00:00 PM
   (3) Team: Manoj, Shift: Night, Start: 03/06/2017 4:00:00 PM, End: 03/07/2017 1:00:00 AM
[7] : Tuesday, March 7, 2017
   (1) Team: Sridhar, Shift: Day, Start: 03/07/2017 7:00:00 AM, End: 03/07/2017 4:00:00 PM
   (2) Team: Ezhil, Shift: Day, Start: 03/07/2017 7:00:00 AM, End: 03/07/2017 4:00:00 PM
   (3) Team: Rajesh, Shift: Night, Start: 03/07/2017 4:00:00 PM, End: 03/08/2017 1:00:00 AM
   (4) Team: Ponram, Shift: Night, Start: 03/07/2017 4:00:00 PM, End: 03/08/2017 1:00:00 AM
[8] : Wednesday, March 8, 2017
   (1) Team: Manoj, Shift: Day, Start: 03/08/2017 7:00:00 AM, End: 03/08/2017 4:00:00 PM
   (2) Team: Sridhar, Shift: Night, Start: 03/08/2017 4:00:00 PM, End: 03/09/2017 1:00:00 AM
   (3) Team: Ezhil, Shift: Night, Start: 03/08/2017 4:00:00 PM, End: 03/09/2017 1:00:00 AM
[9] : Thursday, March 9, 2017
   (1) Team: Rajesh, Shift: Day, Start: 03/09/2017 7:00:00 AM, End: 03/09/2017 4:00:00 PM
   (2) Team: Ponram, Shift: Day, Start: 03/09/2017 7:00:00 AM, End: 03/09/2017 4:00:00 PM
   (3) Team: Manoj, Shift: Night, Start: 03/09/2017 4:00:00 PM, End: 03/10/2017 1:00:00 AM
[10] : Friday, March 10, 2017
   (1) Team: Sridhar, Shift: Day, Start: 03/10/2017 7:00:00 AM, End: 03/10/2017 4:00:00 PM
   (2) Team: Ezhil, Shift: Day, Start: 03/10/2017 7:00:00 AM, End: 03/10/2017 4:00:00 PM
   (3) Team: Rajesh, Shift: Night, Start: 03/10/2017 4:00:00 PM, End: 03/11/2017 1:00:00 AM
   (4) Team: Ponram, Shift: Night, Start: 03/10/2017 4:00:00 PM, End: 03/11/2017 1:00:00 AM
[11] : Saturday, March 11, 2017
   (1) Team: Manoj, Shift: Day, Start: 03/11/2017 7:00:00 AM, End: 03/11/2017 4:00:00 PM
   (2) Team: Sridhar, Shift: Night, Start: 03/11/2017 4:00:00 PM, End: 03/12/2017 1:00:00 AM
   (3) Team: Ezhil, Shift: Night, Start: 03/11/2017 4:00:00 PM, End: 03/12/2017 1:00:00 AM
[12] : Sunday, March 12, 2017
   (1) Team: Rajesh, Shift: Day, Start: 03/12/2017 7:00:00 AM, End: 03/12/2017 4:00:00 PM
   (2) Team: Ponram, Shift: Day, Start: 03/12/2017 7:00:00 AM, End: 03/12/2017 4:00:00 PM
   (3) Team: Manoj, Shift: Night, Start: 03/12/2017 4:00:00 PM, End: 03/13/2017 1:00:00 AM
[13] : Monday, March 13, 2017
   (1) Team: Sridhar, Shift: Day, Start: 03/13/2017 7:00:00 AM, End: 03/13/2017 4:00:00 PM
   (2) Team: Ezhil, Shift: Day, Start: 03/13/2017 7:00:00 AM, End: 03/13/2017 4:00:00 PM
   (3) Team: Rajesh, Shift: Night, Start: 03/13/2017 4:00:00 PM, End: 03/14/2017 1:00:00 AM
   (4) Team: Ponram, Shift: Night, Start: 03/13/2017 4:00:00 PM, End: 03/14/2017 1:00:00 AM
[14] : Tuesday, March 14, 2017
   (1) Team: Manoj, Shift: Day, Start: 03/14/2017 7:00:00 AM, End: 03/14/2017 4:00:00 PM
   (2) Team: Sridhar, Shift: Night, Start: 03/14/2017 4:00:00 PM, End: 03/15/2017 1:00:00 AM
   (3) Team: Ezhil, Shift: Night, Start: 03/14/2017 4:00:00 PM, End: 03/15/2017 1:00:00 AM
[15] : Wednesday, March 15, 2017
   (1) Team: Rajesh, Shift: Day, Start: 03/15/2017 7:00:00 AM, End: 03/15/2017 4:00:00 PM
   (2) Team: Ponram, Shift: Day, Start: 03/15/2017 7:00:00 AM, End: 03/15/2017 4:00:00 PM
   (3) Team: Manoj, Shift: Night, Start: 03/15/2017 4:00:00 PM, End: 03/16/2017 1:00:00 AM
[16] : Thursday, March 16, 2017
   (1) Team: Sridhar, Shift: Day, Start: 03/16/2017 7:00:00 AM, End: 03/16/2017 4:00:00 PM
   (2) Team: Ezhil, Shift: Day, Start: 03/16/2017 7:00:00 AM, End: 03/16/2017 4:00:00 PM
   (3) Team: Rajesh, Shift: Night, Start: 03/16/2017 4:00:00 PM, End: 03/17/2017 1:00:00 AM
   (4) Team: Ponram, Shift: Night, Start: 03/16/2017 4:00:00 PM, End: 03/17/2017 1:00:00 AM
[17] : Friday, March 17, 2017
   (1) Team: Manoj, Shift: Day, Start: 03/17/2017 7:00:00 AM, End: 03/17/2017 4:00:00 PM
   (2) Team: Sridhar, Shift: Night, Start: 03/17/2017 4:00:00 PM, End: 03/18/2017 1:00:00 AM
   (3) Team: Ezhil, Shift: Night, Start: 03/17/2017 4:00:00 PM, End: 03/18/2017 1:00:00 AM
[18] : Saturday, March 18, 2017
   (1) Team: Rajesh, Shift: Day, Start: 03/18/2017 7:00:00 AM, End: 03/18/2017 4:00:00 PM
   (2) Team: Ponram, Shift: Day, Start: 03/18/2017 7:00:00 AM, End: 03/18/2017 4:00:00 PM
   (3) Team: Manoj, Shift: Night, Start: 03/18/2017 4:00:00 PM, End: 03/19/2017 1:00:00 AM
[19] : Sunday, March 19, 2017
   (1) Team: Sridhar, Shift: Day, Start: 03/19/2017 7:00:00 AM, End: 03/19/2017 4:00:00 PM
   (2) Team: Ezhil, Shift: Day, Start: 03/19/2017 7:00:00 AM, End: 03/19/2017 4:00:00 PM
   (3) Team: Rajesh, Shift: Night, Start: 03/19/2017 4:00:00 PM, End: 03/20/2017 1:00:00 AM
   (4) Team: Ponram, Shift: Night, Start: 03/19/2017 4:00:00 PM, End: 03/20/2017 1:00:00 AM
[20] : Monday, March 20, 2017
   (1) Team: Manoj, Shift: Day, Start: 03/20/2017 7:00:00 AM, End: 03/20/2017 4:00:00 PM
   (2) Team: Sridhar, Shift: Night, Start: 03/20/2017 4:00:00 PM, End: 03/21/2017 1:00:00 AM
   (3) Team: Ezhil, Shift: Night, Start: 03/20/2017 4:00:00 PM, End: 03/21/2017 1:00:00 AM
[21] : Tuesday, March 21, 2017
   (1) Team: Rajesh, Shift: Day, Start: 03/21/2017 7:00:00 AM, End: 03/21/2017 4:00:00 PM
   (2) Team: Ponram, Shift: Day, Start: 03/21/2017 7:00:00 AM, End: 03/21/2017 4:00:00 PM
   (3) Team: Manoj, Shift: Night, Start: 03/21/2017 4:00:00 PM, End: 03/22/2017 1:00:00 AM
[22] : Wednesday, March 22, 2017
   (1) Team: Sridhar, Shift: Day, Start: 03/22/2017 7:00:00 AM, End: 03/22/2017 4:00:00 PM
   (2) Team: Ezhil, Shift: Day, Start: 03/22/2017 7:00:00 AM, End: 03/22/2017 4:00:00 PM
   (3) Team: Rajesh, Shift: Night, Start: 03/22/2017 4:00:00 PM, End: 03/23/2017 1:00:00 AM
   (4) Team: Ponram, Shift: Night, Start: 03/22/2017 4:00:00 PM, End: 03/23/2017 1:00:00 AM
[23] : Thursday, March 23, 2017
   (1) Team: Manoj, Shift: Day, Start: 03/23/2017 7:00:00 AM, End: 03/23/2017 4:00:00 PM
   (2) Team: Sridhar, Shift: Night, Start: 03/23/2017 4:00:00 PM, End: 03/24/2017 1:00:00 AM
   (3) Team: Ezhil, Shift: Night, Start: 03/23/2017 4:00:00 PM, End: 03/24/2017 1:00:00 AM
[24] : Friday, March 24, 2017
   (1) Team: Rajesh, Shift: Day, Start: 03/24/2017 7:00:00 AM, End: 03/24/2017 4:00:00 PM
   (2) Team: Ponram, Shift: Day, Start: 03/24/2017 7:00:00 AM, End: 03/24/2017 4:00:00 PM
   (3) Team: Manoj, Shift: Night, Start: 03/24/2017 4:00:00 PM, End: 03/25/2017 1:00:00 AM
[25] : Saturday, March 25, 2017
   (1) Team: Sridhar, Shift: Day, Start: 03/25/2017 7:00:00 AM, End: 03/25/2017 4:00:00 PM
   (2) Team: Ezhil, Shift: Day, Start: 03/25/2017 7:00:00 AM, End: 03/25/2017 4:00:00 PM
   (3) Team: Rajesh, Shift: Night, Start: 03/25/2017 4:00:00 PM, End: 03/26/2017 1:00:00 AM
   (4) Team: Ponram, Shift: Night, Start: 03/25/2017 4:00:00 PM, End: 03/26/2017 1:00:00 AM
[26] : Sunday, March 26, 2017
   (1) Team: Manoj, Shift: Day, Start: 03/26/2017 7:00:00 AM, End: 03/26/2017 4:00:00 PM
   (2) Team: Sridhar, Shift: Night, Start: 03/26/2017 4:00:00 PM, End: 03/27/2017 1:00:00 AM
   (3) Team: Ezhil, Shift: Night, Start: 03/26/2017 4:00:00 PM, End: 03/27/2017 1:00:00 AM
[27] : Monday, March 27, 2017
   (1) Team: Rajesh, Shift: Day, Start: 03/27/2017 7:00:00 AM, End: 03/27/2017 4:00:00 PM
   (2) Team: Ponram, Shift: Day, Start: 03/27/2017 7:00:00 AM, End: 03/27/2017 4:00:00 PM
   (3) Team: Manoj, Shift: Night, Start: 03/27/2017 4:00:00 PM, End: 03/28/2017 1:00:00 AM
[28] : Tuesday, March 28, 2017
   (1) Team: Sridhar, Shift: Day, Start: 03/28/2017 7:00:00 AM, End: 03/28/2017 4:00:00 PM
   (2) Team: Ezhil, Shift: Day, Start: 03/28/2017 7:00:00 AM, End: 03/28/2017 4:00:00 PM
   (3) Team: Rajesh, Shift: Night, Start: 03/28/2017 4:00:00 PM, End: 03/29/2017 1:00:00 AM
   (4) Team: Ponram, Shift: Night, Start: 03/28/2017 4:00:00 PM, End: 03/29/2017 1:00:00 AM
[29] : Wednesday, March 29, 2017
   (1) Team: Manoj, Shift: Day, Start: 03/29/2017 7:00:00 AM, End: 03/29/2017 4:00:00 PM
   (2) Team: Sridhar, Shift: Night, Start: 03/29/2017 4:00:00 PM, End: 03/30/2017 1:00:00 AM
   (3) Team: Ezhil, Shift: Night, Start: 03/29/2017 4:00:00 PM, End: 03/30/2017 1:00:00 AM
[30] : Thursday, March 30, 2017
   (1) Team: Rajesh, Shift: Day, Start: 03/30/2017 7:00:00 AM, End: 03/30/2017 4:00:00 PM
   (2) Team: Ponram, Shift: Day, Start: 03/30/2017 7:00:00 AM, End: 03/30/2017 4:00:00 PM
   (3) Team: Manoj, Shift: Night, Start: 03/30/2017 4:00:00 PM, End: 03/31/2017 1:00:00 AM
   
Requirement is : 
1. If there is a feature / parameter which allows to me mention the number of people required for each shift
2. If there is a feature which can allow different roles (for example I have only provided Master Chef , but I do have roles like Helpers/Driver/etc)

**Comment by point85** [comment]
See release 2.1.0 which has added TeamMember and TeamMemberException functionality to track shift personnel
